apiVersion : apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
  labels:
    app : frontend-deployment
spec:
  selector:
    matchLabels:
      project: frontend
  template:
    metadata:
      labels:
        project: frontend   # Service will look for those PODS Labels!!!
    spec:
      containers:
        - name : frontend-web
          image: undrey/frontend:latest
          ports:
            - containerPort: 5000
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v2beta1v1
    kind: Deployment
    name: frontend-deploy
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 80

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
     env  : prod
     owner: Rubtsov
spec:
  selector:
    project: frontend      # Selecting PODs with those Labels
  ports:
    - name      : app-listener
      protocol  : TCP
      port      : 80  # Port on Load Balancer
      targetPort: 5000  # Port on Pod
  type: LoadBalancer
